---
title: "About"
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

[Vector Symbolic Architectures](https://arxiv.org/abs/2001.11797) 
or [Hyperdimensional Computing](https://doi.org/10.1007/s12559-009-9009-8) systems
are computational systems designed in terms of carefully chosen operators
applied to high-dimensional vector spaces.
VSAs appear to be robust to a wide range of choices of the specific vector space and operators.
This raises the question of which properties are required for VSAs
and how those relate to the choices of vector space and operators.

In this project we construct a reasonable parameterisation of VSA operators
and map out the algebraic properties of VSA operators
as a function location in the parameter space.
To the extent that the practical uitility of VSA operators
follows from their algebraic properties,
this map will help in understanding and designing VSA computational systems.

This project is the joint work of (alphabetically):

* [Charles T. Gray](https://www.linkedin.com/in/charles-gray-mathbassador/)
* [Ross W. Gayler](https://www.rossgayler.com/)
* [Stefan Reimann](https://www.linkedin.com/in/stefanreimann/)

---

We are using the [`{workflowr}`](https://github.com/jdblischak/workflowr) package to structure project 
so that the work is computationally reproducible
and all the materials and outputs are openly accessible.
