---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

This is the research website for the project "VSA operator properties".

The online copy of this site is at https://rgayler.github.io/VSA_op_properties/

---

* [Simulation notebook](simulation.html)

This notebook contains the simulations informing the output paper.
In addition to the code, it also contains notes on the design and implementation of the simulations
and notes on the interpretation of the results.
It is effectively a laboratory notebook,
capturing the process by which we arrived at our conclusions.

The output paper is a separate document
because the presentation of the conclusions
doesn't necessary follow the same path we followed to arrive at the conclusions
and because publication venues have idiosyncratic formatting requirements.

* [Skeleton paper](skeleton.html)

This document sketches out the contents and organisation of the final output paper.
It also contains meta-level discussion of the paper,
including possible future extensions.

* [Output paper](paper.pdf)

*This is currently a dummy paper.*

This is the final form of the output document
that will be uploaded to an appropriate archive
and submitted to a publication venue.

* [Cookbook](cookbook.html)

This document contains useful definitions of HD properties.

